apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-root-route
  namespace: kong
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/preserve-host: "false"
    kubernetes.io/ingress.class: "kong"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: health-check
            port:
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-status-route
  namespace: kong
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/preserve-host: "false"
    kubernetes.io/ingress.class: "kong"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /status
        pathType: Prefix
        backend:
          service:
            name: health-check
            port:
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openai-route
  namespace: default
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/preserve-host: "false"
    kubernetes.io/ingress.class: "kong"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /openai
        pathType: Prefix
        backend:
          service:
            name: openai-service
            port:
              number: 80
