apiVersion: v1
kind: ConfigMap
metadata:
  name: health-check-html
  namespace: kong
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Kong Health Check</title>
    </head>
    <body>
      <h1>Kong is healthy!</h1>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-check
  template:
    metadata:
      labels:
        app: health-check
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: health-check-html

---
apiVersion: v1
kind: Service
metadata:
  name: health-check
  namespace: kong
spec:
  selector:
    app: health-check
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: health-check-ingress
  namespace: kong
  annotations:
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
  - http:
      paths:
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: health-check
            port:
              number: 80