apiVersion: v1
kind: ConfigMap
metadata:
  name: openai-mock-html
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>OpenAI Mock Service</title>
    </head>
    <body>
      <h1>OpenAI Mock Service</h1>
      <p>This is a mock service for OpenAI.</p>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openai-mock
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openai-mock
  template:
    metadata:
      labels:
        app: openai-mock
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: openai-mock-html

---
apiVersion: v1
kind: Service
metadata:
  name: openai-service
  namespace: default
spec:
  selector:
    app: openai-mock
  ports:
  - port: 80
    targetPort: 80