cat openai-pipeline.yml 
trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  subscription_id: '955faad9-ebe9-4a85-9974-acae429ae877'
  resource_group_name: 'openai-rg'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    backendServiceArm: 'azure-service-connection'
    backendAzureRmResourceGroupName: '$(resource_group_name)'
    backendAzureRmStorageAccountName: 'tfstate-storage'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'appgw.tfstate'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    environmentServiceNameAzureRM: 'azure-service-connection'
    commandOptions: '-var "subscription_id=$(subscription_id)" -auto-approve'
